### ISSUE TITLE
Fail to open if an element includes too many points

### ISSUE THREAD

**Issue by TsuITOAR** [dan-fritchman/Layout21#1]
Thanks for creating this crate.
I've run into a problem that if I created an element with a vast number of points, Klayout would alert that ` invalid record length (less than 4)`.
For example

```
    use gds21::*;
    let mut lib = GdsLibrary::new("mylib");
    let mut newcell = GdsStruct::new("mycell");
    let n=100000;
    newcell.elems.push(GdsElement::GdsBoundary(GdsBoundary {
        layer: 0,
        datatype: 0,
        xy: (1..=n).into_iter().chain(vec![100,150,1,2].into_iter()).collect(),
        ..GdsBoundary::default()
    }));
    lib.structs.push(newcell);
    lib.save("example.gds")?;
    Ok(())
```

this would work with n=10000, but fail with n=100000.

I was trying to draw a circle, and the circle generated will fail even with n=10000 (n=5000 works).

```
    use gds21::*;
    use ndarray::{array, Array};
    use std::f64::consts::PI;
    let mut lib = GdsLibrary::new("mylib");
    let mut newcell = GdsStruct::new("mycell");
    let user_unit = 1e-6;
    let db_unit = 1e-9;
    let scale = user_unit / db_unit;
    let units = GdsUnits::new(1. / scale, db_unit);
    lib.units = units;
    let circle_radius = 300.;
    //let resolution = 100e-3;
    //let n=(2. * PI * circle_radius / resolution) as usize;
    let n = 10000;
    let arg_list = Array::linspace(0., 2. * PI, n + 1);
    let point_list =
        arg_list.map(|arg| array![(arg.cos() * circle_radius), (arg.sin() * circle_radius),]);
    newcell.elems.push(GdsElement::GdsBoundary(GdsBoundary {
        layer: 0,
        datatype: 0,
        xy: point_list
            .iter()
            .flatten()
            .copied()
            .map(|x| (x * scale) as i32)
            .collect(),
        ..GdsBoundary::default()
    }));
    lib.structs.push(newcell);
    lib.save("example.gds")?;
    Ok(())
```

I want to know that if this is a limit of GDSII or it's a bug that you could fix?

**Comment by dan-fritchman** [comment]
Glad you've found it helpful! (As you can see it's early days.)  

Wanted to clarify what happens for you: 
* In both cases, gds21 produces a layout and writes it to file
* In the larger case, *Klayout* fails to open said layout-file
Correct?  

As far as GDSII is concerned, I believe **both** cases should fail. The [spec](http://bitsavers.informatik.uni-stuttgart.de/pdf/calma/GDS_II_Stream_Format_Manual_6.0_Feb87.pdf) says:  

```
Path and boundary elements may have up to 200 pairs of coordinates. 
```

Now, this is almost certainly a point where the letter-of-the-law is not being followed in practice, by nearly *any* GDSII-consuming application. I can't speak for Klayout, but gds21 imposes no such limit on the length of x-y coordinates. It'll let you freely add them forever (or until you run out of memory). Other applications likely differ in all sorts of ways. ["The" LayoutEditor](https://layouteditor.com) is another which I really like, and may be worth checking their handling of these high-resolution shapes.

**Comment by TsuITOAR** [comment]
> Glad you've found it helpful! (As you can see it's early days.)
> 
> Wanted to clarify what happens for you:
> 
> * In both cases, gds21 produces a layout and writes it to file
> * In the larger case, _Klayout_ fails to open said layout-file
>   Correct?
> 
> As far as GDSII is concerned, I believe **both** cases should fail. The [spec](http://bitsavers.informatik.uni-stuttgart.de/pdf/calma/GDS_II_Stream_Format_Manual_6.0_Feb87.pdf) says:
> 
> ```
> Path and boundary elements may have up to 200 pairs of coordinates. 
> ```
> 
> Now, this is almost certainly a point where the letter-of-the-law is not being followed in practice, by nearly _any_ GDSII-consuming application. I can't speak for Klayout, but gds21 imposes no such limit on the length of x-y coordinates. It'll let you freely add them forever (or until you run out of memory). Other applications likely differ in all sorts of ways. ["The" LayoutEditor](https://layouteditor.com) is another which I really like, and may be worth checking their handling of these high-resolution shapes.

Thanks for your suggestion.
I've tried LayoutEditor and it cracked opening the file. Ledit says `can't read design file "\xxx.gds" entirely`. 
I think the problem is the file itself.

**Comment by TsuITOAR** [comment]
Erro log in Ledit:

> Option Settings:
> Treat unique GDS data types on a layer as different layers: ON
> Using original GDSII database resolution: 0.001 microns
> 
> Warning #33: Found unknown GDSII layer 0 (Action: Created a new layer GDS_00_DT_00 for GDSII number 0 and Data type 0)
> Error #11: Invalid boundary:  First and last coordinates do NOT coincide.
> (In cell "mycell" on layer "GDS_00_DT_00".)
> 	299999, 0
> 	299999, 188
> 	299999, 376
> 	299999, 565
> 	299999, 753
> 	299998, 942
> 	299997, 1130
> 	299997, 1319
> 	299996, 1507
> 	299995, 1696
> 	299994, 1884

......

> 	126880, 271848
> 	126709, 271927
> 	126538, 272007
> 	126367, 272086
> 	 (Action: Reading will be aborted.)
> Error #4: Unexpected elem. in byte-skip.
> File Position 14598, Record Length 1
> Record type 236, Data type 244 (Action: Import Aborted)

**Comment by TsuITOAR** [comment]
The limit of the number of points in a polygon should be 8191, thanks for your help again.
Looking forward to `layout21`

**Comment by dan-fritchman** [comment]
Having looked at this some more, there is a more fundamental fact which limits the length to 8191 for *any* GDSII. 

* The `len` field of each GdsRecord is a 16-bit unsigned integer. 
* Records are therefore limited to 2**16 = 64kB (including a few header bytes).
* `Xy` records store coordinates in four-byte integers. 
* Each can therefore contain up to (64k / 4) = 16k numbers, or 8k coordinate-pairs. 
* (The real limit may actually be 8190 rather than 8191, accounting for the header bytes.) 

Gds21 is not checking for this before writing to `GdsRecords`.  
It probably should.

**Comment by dan-fritchman** [comment]
Commit https://github.com/dan-fritchman/Layout21/commit/e695ab27296cf921f2e2438c4a53092e4f26a917 has the stuff to reject these invalid records. And a test-case derived from your example code. Thanks very much for digging in here and providing that!
