### ISSUE TITLE
GDS loading could panick at "invalid or out-of-range date".

### ISSUE THREAD

**Issue by EMUNES** [dan-fritchman/Layout21#19]
Really glad to find a layout data parsing project based on rust. It's really good and brings a lot of convenience and fun. I want to mention a problem I met when I use this library.

I try to read some gds library files. My code: 

```
use gds21::{GdsLibrary, GdsStruct};
#[test]
fn gds_loading() {
    let lib = GdsLibrary::load("assets/data/gds/AND2X2.gds");
    dbg!(lib.unwrap());
}
```

And it panicked, showing: `thread 'gds_loading' panicked at 'invalid or out-of-range date'`.

I think this could be related to GDS datetime. And when I test on other libaray gds files it could happen too. I haven't digged it deep yet. If more info is needed please let me know.

Environment:

- rust: 1.63
- gds21: 0.2.0
- on pop-os 22.04

Bests.

**Comment by dan-fritchman** [comment]
Glad you like it! 

I suppose the question is: does that GDS file in fact have an “invalid or out of range date”? 

Each GDS file/ library and each of its cells/ structs have embedded creation & last-modification times. It appears we are finding the to be invalid, e.g. with “month 14” or “day 50”. 

Would you be able to share that AND2x2.gds, or at least (somehow) its embedded date values? (Not sure how you’d do the latter; perhaps another viewer such as Klayout or Calibre would show them.)

**Comment by EMUNES** [comment]
OK. Somehow I can't see the date in Klayout. I can share the file. Thanks.
[AND2X2.zip](https://github.com/dan-fritchman/Layout21/files/9482072/AND2X2.zip)

**Comment by dan-fritchman** [comment]
Yep, I reproduce this just the same. 

The complaint is that the GDSII file has (0,0,0) for the (year, month, day) fields in its creation time. The [chrono Date objects](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html) we convert them to do not like either the month or day being zero. They apparently want 1-12 and 1-31 instead. And, at least given how we invoke them, invalid values generate a panic. 

This will likely spur some changes to Gds21/ Layout21. In the meantime, are you able to share what generated this GDS file? A commercial layout tool, or some custom software? 

Maybe notable: the (hours, minutes, seconds) of those same GDSII date-time fields are valid values: (17,49,18).

**Comment by EMUNES** [comment]
Thanks. Now I know clearly where the problem is. 

I think it's from gscl 45nm or FreePDK 45nm, a set of open source pdk. Hope it helps:) 

I would like to share more info but I don't know what tools the author exactly used to make them. From Klayout I think those gds files do work well except datetime problems. Maybe they do this intentionally for some reason. Thanks for your work.

**Comment by dan-fritchman** [comment]
Yep, my own versions of Klayout and "The" LayoutEditor load it too.  
That's in large part why I'd like this to spur some changes to Gds21: clearly other tools are either treating these dates as valid, or ignoring them. (I suspect the latter.)

**Comment by dan-fritchman** [comment]
Alright, if it works for you to depend on a git-branch, this should get you going:  
https://github.com/dan-fritchman/Layout21/tree/v021

Absent an urgent need for that on crates.io, we'll roll it into the next releases.

**Comment by EMUNES** [comment]
Great! Thanks for your work:)
