### ISSUE TITLE
klayout cannot open lef21 generated LEF because of 'DATABASE ...' line

### ISSUE THREAD

**Issue by growly** [dan-fritchman/Layout21#32]
![image](https://user-images.githubusercontent.com/125257/205479169-5cd8e63d-9f09-4087-a401-442923086d0e.png)

LEF file:
[test.lef.zip](https://github.com/dan-fritchman/Layout21/files/10148045/test.lef.zip)

**Comment by dan-fritchman** [comment]
Linking https://github.com/KLayout/klayout/issues/1208

**Comment by dan-fritchman** [comment]
Recommend closing in favor of https://github.com/KLayout/klayout/issues/1208. 

As discussed there, `UNITS` and `DATABASE` are all very-valid LEF content. This was largely a misunderstanding about how Klayout is expecting to use LEF.
