### ISSUE TITLE
Deriving Enum for EnumMap on GdsElement

### ISSUE THREAD

**Issue by kunalchandan** [dan-fritchman/Layout21#42]
# Problem Statement
Hi,
I'm new to Rust, and am using this library to work on a project. For the project I want to be able to use `GdsElement` as a key in some sort of dictionary like mapping, I think `EnumMap` is the way to go.

# Reasoning
https://stackoverflow.com/questions/63093321/why-does-rust-prevent-implementing-an-external-trait-for-an-external-struct

Suggests using the `newtype` idiom, however, applying that to a struct wrapper of `enum GdsElement` led to the same problem where the `enum GdsElement` required the `Enum` trait.

# Solution
Adding `enum_map` as a dependency for `gds21` and adding the `Enum` trait to the derive statement of `GdsElement`

```rust
use enum_map::Enum;

...

#[derive(derive_more::From, Debug, Clone, Deserialize, Serialize, PartialEq, Enum)]
pub enum GdsElement {
    GdsBoundary(GdsBoundary),
    GdsPath(GdsPath),
    GdsStructRef(GdsStructRef),
    GdsArrayRef(GdsArrayRef),
    GdsTextElem(GdsTextElem),
    GdsNode(GdsNode),
    GdsBox(GdsBox),
}
```

This could also simplify the code for the `GdsStruct stats` function

Please let me know if this is a silly idea, I'm still new to the language and am learning. I have found your library quite helpful!

**Comment by dan-fritchman** [comment]
Hi Kunal - glad you're finding it helpful!  
I'm not sure I quite follow either the target use-case, or the proposed implementation - maybe you can help me understand. 

> For the project I want to be able to use GdsElement as a key in some sort of dictionary like mapping, I think EnumMap is the way to go.

What kinda "dictionary like mapping" do you have in mind here? Like [std::collections::HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html)? And what kinda stuff do you imagine mapping _to_? (And why?) 

I.e. what would be the `Something` here: 

```rust
some_sort_of_dictionary_like_mapping: HashMap<GdsElement, Something>; // <= what's the `Something`?
```

Second, if you have such a mapping, do you want equal-valued but distinct `GdsElement`s to behave as "hits" or "misses" in that map? If you want to map from _distinct_ shapes - i.e. "equivalent but distinct" shapes are _misses_, then hashing them by address probably works. If not, *maybe* they could implement the std-lib [Hash trait](https://doc.rust-lang.org/std/hash/trait.Hash.html) on their inner data. But many of the variants store unhashable inner data, e.g. `Polygon` stores a `Vec` of `Point`s. 

In either case, I'm not sure I see how that `enum_map` crate helps. It's docs here https://docs.rs/enum-map/latest/enum_map/struct.EnumMap.html say:

> This internally uses an array which stores a value for each possible enum value.

`GdsElement` quite literally has an infinite number of possible values - as noted above, many store arbitrary-length vectors of `Point`s.  

Maybe you mean a mapping to something like a `GdsElementKind` or `GdsElementType`, a "unit enum" or "C-style enum" along the lines of: 

```rust 
/// Just the kinds, no data
pub enum GdsElementKind {
    GdsBoundary,
    GdsPath,
    GdsStructRef,
    GdsArrayRef,
    GdsTextElem,
    GdsNode,
    GdsBox,
}
```

**Comment by kunalchandan** [comment]
Hi Dan,

Thank you very much for the speedy response. I needed some time to understand. I really did need something like `GdsElementKind`/`GdsElementType` where I wanted all `GdsElement`s of a type to hit the same mapping.

I want to be able to do something like get the physical layout areas of each of the various types, but thinking about that further, I should probably do something like what you've done with `GdsStats` and separately implement the area function for each of the enums.

```
match elem {
    GdsBoundary(_) => stats.boundaries += 1,
    GdsPath(_) => stats.paths += 1,
    GdsStructRef(_) => stats.struct_refs += 1,
    GdsArrayRef(_) => stats.array_refs += 1,
    GdsTextElem(_) => stats.text_elems += 1,
    GdsNode(_) => stats.nodes += 1,
    GdsBox(_) => stats.boxes += 1,
};
```
Thanks for taking the time to respond! I think it would be ok to close this.
