### ISSUE TITLE
Surprise to see Layout21 become much greater

### ISSUE THREAD

**Issue by erihsu** [dan-fritchman/Layout21#6]
Hi fritchman,
 I notice your crate about half-year ago, today I find now Layout21 support the gds2/lef parse/write, very impressive by your work. I am interested in PD & Rust and  I write a simple [gds2 parser](https://github.com/erihsu/gds2-parser) in rust long time ago. Any further plans for this crate? I am willing to help if possible.

**Comment by dan-fritchman** [comment]
Very kind of you thanks, and great to hear. 
Why don’t we move to exchanging email (dan@fritch.mn) and we can chat about future work.
